// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ00qullOco9P7VIOa8jE923Tmcxc0n-M',
    appId: '1:137557676548:web:7433556834855bc0645b51',
    messagingSenderId: '137557676548',
    projectId: 'crypto-analytics-133e5',
    authDomain: 'crypto-analytics-133e5.firebaseapp.com',
    storageBucket: 'crypto-analytics-133e5.appspot.com',
    measurementId: 'G-WGNCXMR371',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3K_UGTS6FSamsFcvN1c--zXcTfM01gW0',
    appId: '1:137557676548:android:b1427c6c8c215b65645b51',
    messagingSenderId: '137557676548',
    projectId: 'crypto-analytics-133e5',
    storageBucket: 'crypto-analytics-133e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkhY3Wqna-e213gGMjWZ8Us5e1Jbc_ruY',
    appId: '1:137557676548:ios:6d75897ef394e668645b51',
    messagingSenderId: '137557676548',
    projectId: 'crypto-analytics-133e5',
    storageBucket: 'crypto-analytics-133e5.appspot.com',
    iosClientId: '137557676548-rr09teq57febljusaq24k0t89qsa9cca.apps.googleusercontent.com',
    iosBundleId: 'com.example.cryptoAnalytics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkhY3Wqna-e213gGMjWZ8Us5e1Jbc_ruY',
    appId: '1:137557676548:ios:6205b07e0b6b21c0645b51',
    messagingSenderId: '137557676548',
    projectId: 'crypto-analytics-133e5',
    storageBucket: 'crypto-analytics-133e5.appspot.com',
    iosClientId: '137557676548-024slpqe0vckt2bj68blugmdm7f4b9n8.apps.googleusercontent.com',
    iosBundleId: 'com.example.cryptoAnalytics.RunnerTests',
  );
}
